
Sun, 31 Jan 2010 09:01:31 GMT

MAKE:
mv pidigits.python3-4.python3 pidigits.python3-4.py
/usr/local/src/Python-3.1.1/bin/python3.1 -OO -c "from py_compile import compile; compile('pidigits.python3-4.py')"
0.07s to complete and log all make actions

COMMAND LINE:
/usr/local/src/Python-3.1.1/bin/python3.1 pidigits.python3-4.pyo 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.python3-4.py", line 7, in <module>
    import gmpy
ImportError: No module named gmpy
