
Mon, 20 Apr 2009 12:13:14 GMT

COMMAND LINE:
/usr/local/src/pypy-dist/pypy-c pidigits.pypy-4.pypy 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "?", line 33, in run_toplevel
  File "pidigits.pypy-4.pypy", line 7, in <module>
    import gmpy
ImportError: No module named gmpy
