
Wed, 28 Jan 2009 00:38:02 GMT

MAKE:
mv pidigits.python3-4.python3 pidigits.python3-4.py
/usr/local/src/Python-3.0/python -OO -c "from py_compile import compile; compile('pidigits.python3-4.py')"
0.04s to complete and log all make actions

COMMAND LINE:
/usr/local/src/Python-3.0/python pidigits.python3-4.pyo 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.python3-4.py", line 8, in <module>
    import gmpy
ImportError: No module named gmpy
