
Fri, 12 Mar 2010 23:11:47 GMT

COMMAND LINE:
/usr/local/src/pypy-1.2/bin/pypy pidigits.pypy-4.pypy 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "?", line 33, in run_toplevel
  File "pidigits.pypy-4.pypy", line 7, in <module>
    import gmpy
ImportError: No module named gmpy
