
Sun, 27 Jun 2010 16:13:43 GMT

COMMAND LINE:
/usr/local/src/pypy-1.3/bin/pypy pidigits.pypy-4.pypy 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 33, in run_toplevel
  File "pidigits.pypy-4.pypy", line 7, in <module>
    import gmpy
ImportError: No module named gmpy
