
Tue, 27 Jan 2009 08:46:54 GMT

MAKE:
mv pidigits.python3-3.python3 pidigits.python3-3.py
/usr/local/src/Python-3.0/python -OO -c "from py_compile import compile; compile('pidigits.python3-3.py')"
0.04s to complete and log all make actions

COMMAND LINE:
/usr/local/src/Python-3.0/python pidigits.python3-3.pyo 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.python3-3.py", line 11, in <module>
    import gmpy
ImportError: No module named gmpy
