
Mon, 27 Dec 2010 20:00:07 GMT

COMMAND LINE:
/usr/local/src/pypy-1.4.1-linux64/bin/pypy pidigits.pypy-3.pypy 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 53, in run_toplevel
  File "pidigits.pypy-3.pypy", line 10, in <module>
    import gmpy
ImportError: No module named gmpy
