
Sat, 27 Nov 2010 01:58:27 GMT

COMMAND LINE:
/usr/local/src/pypy-1.4/bin/pypy pidigits.pypy-3.pypy 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 33, in run_toplevel
  File "pidigits.pypy-3.pypy", line 10, in <module>
    import gmpy
ImportError: No module named gmpy
