
Mon, 27 Dec 2010 20:14:45 GMT

COMMAND LINE:
/usr/local/src/pypy-1.4.1-linux64/bin/pypy spectralnorm.pypy-5.pypy 500

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 53, in run_toplevel
  File "spectralnorm.pypy-5.pypy", line 9, in <module>
    from multiprocessing import Pool
ImportError: No module named multiprocessing
