
Tue, 21 Apr 2009 02:48:39 GMT

MAKE:
mv pidigits.python3-4.python3 pidigits.python3-4.py
/usr/local/src/Python-3.1a2/bin/python3.1 -OO -c "from py_compile import compile; compile('pidigits.python3-4.py')"
0.07s to complete and log all make actions

COMMAND LINE:
/usr/local/src/Python-3.1a2/bin/python3.1 pidigits.python3-4.pyo 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.python3-4.py", line 8, in <module>
    import gmpy
ImportError: No module named gmpy
